name: Some Jobs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      some_output: some-value
    steps:
      - run: echo "Hello from job1"
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - run: echo "Hello from job2"
      - run: echo "${{ toJson(needs) }}"
      - run: echo "${{ needs.job1.outputs.some_output }}"
