name: Matrix

on:
  push:
    branches:
      - main

jobs:
  test-parallel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [test, dev]
    steps:
      - run: echo "${{ toJson(matrix) }}"
      - run: echo "${{ matrix.env }}"
