name: Matrix

on:
  push:
    branches:
      - main

jobs:
  test-parallel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - run: echo "${{ toJson(matrix) }}"
      - run: echo "${{ matrix.os }}"
