name: Node in Matrix

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: echo "Running on ${{ matrix.os }} with Node.js ${{ matrix.node-version }}"

      - name: Install my own dependency
        # if: ${{ matrix.node-version == '16.x' }}
        env:
          MY_VER: "${{ matrix.node-version }}"
        run: |
          if [ "${MY_VER}" == "16.x" ]; then
            echo "run.."
            echo "commands.."
          fi
