name: Task 2

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "building..."
  test:
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - run: |
          echo "testing..."
          echo "running on ${{ matrix.os }}"
  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "packaging..."
